export const visualPages = [
  { name: "login", path: "/login", heading: /AI、算法、代码能力/ },
  { name: "homepage", path: "/", heading: "Roky Learn" },
  { name: "today", path: "/today", heading: "今日学习" },
  { name: "review", path: "/review", heading: /复习/ },
  { name: "coach", path: "/coach", heading: "思路评审" },
  { name: "voice", path: "/voice", heading: "语音学习捕获" },
  { name: "map", path: "/map", heading: "知识地图" },
  { name: "glossary", path: "/glossary", heading: "术语库" },
  { name: "radar", path: "/radar", heading: "AI Radar" },
  { name: "projects", path: "/projects", heading: "项目实践" },
  { name: "projects-portfolio", path: "/projects/portfolio", heading: "项目作品集" },
  { name: "path", path: "/path", heading: "学习路径" },
  { name: "weekly", path: "/weekly", heading: "每周复盘" },
  { name: "mistakes", path: "/mistakes", heading: "错题误区" },
  { name: "progress", path: "/progress", heading: "学习进度" },
  { name: "settings", path: "/settings", heading: "设置" },
  { name: "library", path: "/library", heading: "课程库" },
] as const;
