import type { GlossarySeedTerm } from "@/server/knowledge/base";

export const DEFAULT_GLOSSARY_TERMS: GlossarySeedTerm[] = [
  {
    slug: "cot",
    abbreviation: "CoT",
    fullName: "Chain-of-Thought",
    chineseName: "思维链",
    category: "prompting",
    oneLine: "让模型显式组织中间推理步骤的提示方式。",
    explanation: "CoT 用分步推理来处理多跳问题、数学题和复杂判断，重点是让推理过程更可检查。",
    whyImportant: "它是理解复杂推理、Agent 规划和评测误差分析的基础术语。",
    relatedTerms: ["ToT", "ReAct", "Reasoning"],
    commonMistakes: ["把 CoT 当成答案质量保证；实际仍需要验证。"],
    examples: ["先列出已知条件，再分步推出结论。"],
    sourceRefs: [{ title: "Chain-of-Thought Prompting", url: "https://arxiv.org/abs/2201.11903" }],
    difficulty: "beginner",
  },
  {
    slug: "react",
    abbreviation: "ReAct",
    fullName: "Reasoning and Acting",
    chineseName: "推理与行动",
    category: "agent",
    oneLine: "把推理步骤和工具行动交替组织的 Agent 范式。",
    explanation: "ReAct 让模型在思考、调用工具、观察结果之间循环，适合问答、检索和任务执行。",
    whyImportant: "它是理解工具调用 Agent 的入门框架。",
    relatedTerms: ["CoT", "Tool Calling", "Agent"],
    commonMistakes: ["以为 ReAct 必须暴露完整推理；产品中可只保存行动轨迹。"],
    examples: ["Thought -> Action(search) -> Observation -> Answer"],
    sourceRefs: [{ title: "ReAct", url: "https://arxiv.org/abs/2210.03629" }],
    difficulty: "beginner",
  },
  {
    slug: "tot",
    abbreviation: "ToT",
    fullName: "Tree of Thoughts",
    chineseName: "思维树",
    category: "reasoning",
    oneLine: "把多个候选推理路径组织成树并进行搜索。",
    explanation: "ToT 通过展开、评估和回溯多个思路，提升复杂任务中的规划能力。",
    whyImportant: "它帮助区分线性推理和搜索式推理。",
    relatedTerms: ["CoT", "Search", "Planning"],
    commonMistakes: ["把 ToT 当成普通多轮提示，而忽略候选路径评估。"],
    examples: ["为同一题生成三条解法，再评估哪条更稳。"],
    sourceRefs: [{ title: "Tree of Thoughts", url: "https://arxiv.org/abs/2305.10601" }],
    difficulty: "intermediate",
  },
  {
    slug: "reflexion",
    fullName: "Reflexion",
    chineseName: "反思式强化",
    category: "agent",
    oneLine: "让 Agent 根据失败经验写入反思并改进下一次尝试。",
    explanation: "Reflexion 通过语言形式的反馈记忆改善 Agent 的后续决策，而不是直接更新模型参数。",
    whyImportant: "它是长期学习型 Agent 和错误本设计的关键概念。",
    relatedTerms: ["Agent", "Memory", "Self-Reflection"],
    commonMistakes: ["把反思文本当成永久真理；它也需要过期和验证。"],
    examples: ["任务失败后记录：下一次先检查 API 参数。"],
    sourceRefs: [{ title: "Reflexion", url: "https://arxiv.org/abs/2303.11366" }],
    difficulty: "intermediate",
  },
  {
    slug: "rag",
    abbreviation: "RAG",
    fullName: "Retrieval-Augmented Generation",
    chineseName: "检索增强生成",
    category: "retrieval",
    oneLine: "先检索外部资料，再让模型基于资料生成答案。",
    explanation: "RAG 把知识查找和语言生成分开，降低纯参数记忆带来的过期和幻觉风险。",
    whyImportant: "它是企业知识库、搜索问答和文档助手的核心架构。",
    relatedTerms: ["Embedding", "Vector Database", "Reranker"],
    commonMistakes: ["以为接入向量库就是 RAG；检索质量和引用约束同样关键。"],
    examples: ["用户问政策，系统先检索政策文档，再生成带引用的回答。"],
    sourceRefs: [{ title: "Retrieval-Augmented Generation", url: "https://arxiv.org/abs/2005.11401" }],
    difficulty: "beginner",
  },
  {
    slug: "rlhf",
    abbreviation: "RLHF",
    fullName: "Reinforcement Learning from Human Feedback",
    chineseName: "基于人类反馈的强化学习",
    category: "alignment",
    oneLine: "用人类偏好反馈训练模型更符合用户期望。",
    explanation: "RLHF 通常包含偏好数据、奖励模型和强化学习优化，用于改善回答风格与安全性。",
    whyImportant: "它是理解 ChatGPT 类模型对齐流程的基础。",
    relatedTerms: ["SFT", "DPO", "Preference Model"],
    commonMistakes: ["把 RLHF 等同于全部对齐；实际还有数据、规则和评测。"],
    examples: ["比较两个回答，标注哪个更有帮助。"],
    sourceRefs: [{ title: "InstructGPT", url: "https://arxiv.org/abs/2203.02155" }],
    difficulty: "intermediate",
  },
  {
    slug: "dpo",
    abbreviation: "DPO",
    fullName: "Direct Preference Optimization",
    chineseName: "直接偏好优化",
    category: "alignment",
    oneLine: "直接用偏好对优化模型，无需显式训练奖励模型。",
    explanation: "DPO 把偏好学习转成更直接的监督式目标，常用于指令模型对齐。",
    whyImportant: "它是 RLHF 之外常见的偏好优化路径。",
    relatedTerms: ["RLHF", "SFT", "Preference Data"],
    commonMistakes: ["认为 DPO 不需要高质量偏好数据；数据质量仍是关键。"],
    examples: ["给定 chosen/rejected 两个回答对进行训练。"],
    sourceRefs: [{ title: "Direct Preference Optimization", url: "https://arxiv.org/abs/2305.18290" }],
    difficulty: "intermediate",
  },
  {
    slug: "sft",
    abbreviation: "SFT",
    fullName: "Supervised Fine-Tuning",
    chineseName: "监督微调",
    category: "training",
    oneLine: "用标注好的输入输出样本微调模型。",
    explanation: "SFT 让基础模型学习特定任务格式、风格和行为，是许多对齐流程的早期阶段。",
    whyImportant: "它连接预训练模型和可用助手行为。",
    relatedTerms: ["RLHF", "DPO", "Instruction Tuning"],
    commonMistakes: ["以为 SFT 可以补足所有推理能力；它更多塑造行为格式。"],
    examples: ["用问答样本训练模型按指定格式回答。"],
    sourceRefs: [{ title: "InstructGPT", url: "https://arxiv.org/abs/2203.02155" }],
    difficulty: "beginner",
  },
  {
    slug: "lora",
    abbreviation: "LoRA",
    fullName: "Low-Rank Adaptation",
    chineseName: "低秩适配",
    category: "fine-tuning",
    oneLine: "通过低秩矩阵更新少量参数来高效微调模型。",
    explanation: "LoRA 冻结原模型权重，只训练小规模适配矩阵，从而降低显存和存储成本。",
    whyImportant: "它是个人和小团队微调大模型的重要方法。",
    relatedTerms: ["QLoRA", "Fine-Tuning", "Adapters"],
    commonMistakes: ["以为 LoRA 一定接近全量微调；效果取决于任务和配置。"],
    examples: ["为特定写作风格训练一个 LoRA adapter。"],
    sourceRefs: [{ title: "LoRA", url: "https://arxiv.org/abs/2106.09685" }],
    difficulty: "intermediate",
  },
  {
    slug: "qlora",
    abbreviation: "QLoRA",
    fullName: "Quantized Low-Rank Adaptation",
    chineseName: "量化低秩适配",
    category: "fine-tuning",
    oneLine: "结合量化和 LoRA 的低资源微调方法。",
    explanation: "QLoRA 使用量化基础模型并训练 LoRA 参数，进一步降低显存需求。",
    whyImportant: "它让较大模型微调更接近普通 GPU 环境。",
    relatedTerms: ["LoRA", "Quantization", "Fine-Tuning"],
    commonMistakes: ["忽略量化带来的数值和速度权衡。"],
    examples: ["用 4-bit 基础模型训练任务 adapter。"],
    sourceRefs: [{ title: "QLoRA", url: "https://arxiv.org/abs/2305.14314" }],
    difficulty: "advanced",
  },
  {
    slug: "moe",
    abbreviation: "MoE",
    fullName: "Mixture of Experts",
    chineseName: "专家混合",
    category: "architecture",
    oneLine: "用路由器为不同 token 选择部分专家网络参与计算。",
    explanation: "MoE 通过稀疏激活扩大参数规模，同时控制每次推理的计算量。",
    whyImportant: "它是理解现代大模型扩展效率的重要架构。",
    relatedTerms: ["Routing", "Sparse Activation", "Transformer"],
    commonMistakes: ["把总参数量和每次计算量混为一谈。"],
    examples: ["每个 token 只路由到 top-2 experts。"],
    sourceRefs: [{ title: "Switch Transformers", url: "https://arxiv.org/abs/2101.03961" }],
    difficulty: "advanced",
  },
  {
    slug: "swe-bench",
    abbreviation: "SWE-bench",
    fullName: "SWE-bench",
    chineseName: "软件工程基准",
    category: "benchmark",
    oneLine: "评测模型解决真实 GitHub issue 的软件工程能力。",
    explanation: "SWE-bench 用真实项目中的 issue 和补丁检验模型能否理解代码库并修复问题。",
    whyImportant: "它比简单代码题更接近真实工程 Agent 能力。",
    relatedTerms: ["Agent", "Benchmark", "Code Repair"],
    commonMistakes: ["只看分数，不看是否使用了真实可运行环境和评测协议。"],
    examples: ["给模型一个 repo issue，让它提交可通过测试的补丁。"],
    sourceRefs: [{ title: "SWE-bench", url: "https://www.swebench.com/" }],
    difficulty: "intermediate",
  },
  {
    slug: "humaneval",
    abbreviation: "HumanEval",
    fullName: "HumanEval",
    chineseName: "代码生成评测集",
    category: "benchmark",
    oneLine: "用 Python 函数题评测代码生成能力。",
    explanation: "HumanEval 通过 docstring、函数签名和隐藏测试评估模型补全函数的正确率。",
    whyImportant: "它是理解代码模型早期能力对比的常见基准。",
    relatedTerms: ["Code Generation", "pass@k", "MBPP"],
    commonMistakes: ["把 HumanEval 高分等同于真实软件工程能力。"],
    examples: ["根据函数说明实现一个 Python 函数。"],
    sourceRefs: [{ title: "Evaluating Large Language Models Trained on Code", url: "https://arxiv.org/abs/2107.03374" }],
    difficulty: "beginner",
  },
  {
    slug: "mmlu",
    abbreviation: "MMLU",
    fullName: "Massive Multitask Language Understanding",
    chineseName: "大规模多任务语言理解",
    category: "benchmark",
    oneLine: "覆盖多学科选择题的通用知识评测。",
    explanation: "MMLU 包含多个学科和难度层级，用来评估模型的广泛知识和问题理解。",
    whyImportant: "它是大模型通用能力对比中的常见指标。",
    relatedTerms: ["Benchmark", "Multiple Choice", "General Knowledge"],
    commonMistakes: ["把选择题知识能力等同于可执行任务能力。"],
    examples: ["医学、法律、数学等多领域选择题。"],
    sourceRefs: [{ title: "MMLU", url: "https://arxiv.org/abs/2009.03300" }],
    difficulty: "beginner",
  },
  {
    slug: "gpqa",
    abbreviation: "GPQA",
    fullName: "Graduate-Level Google-Proof Q&A",
    chineseName: "研究生级问答评测",
    category: "benchmark",
    oneLine: "面向高难科学问题的问答评测集。",
    explanation: "GPQA 设计为即使搜索也不容易直接回答，用于测试高难专业推理能力。",
    whyImportant: "它常用于观察模型在专家级知识问题上的表现。",
    relatedTerms: ["Benchmark", "Reasoning", "Science QA"],
    commonMistakes: ["忽略题目专业性和评测协议差异。"],
    examples: ["化学、物理、生物等研究生级问题。"],
    sourceRefs: [{ title: "GPQA", url: "https://arxiv.org/abs/2311.12022" }],
    difficulty: "advanced",
  },
  {
    slug: "gsm8k",
    abbreviation: "GSM8K",
    fullName: "Grade School Math 8K",
    chineseName: "小学数学文字题评测",
    category: "benchmark",
    oneLine: "用于评估多步数学文字题推理能力的数据集。",
    explanation: "GSM8K 包含需要逐步推理的数学应用题，经常用于比较模型算术与推理表现。",
    whyImportant: "它是理解 CoT 和推理模型评测的入门基准。",
    relatedTerms: ["CoT", "Math Reasoning", "Benchmark"],
    commonMistakes: ["只看最终答案，不检查推理链是否可靠。"],
    examples: ["购物、分组、比例等文字题。"],
    sourceRefs: [{ title: "GSM8K", url: "https://arxiv.org/abs/2110.14168" }],
    difficulty: "beginner",
  },
  {
    slug: "agent",
    fullName: "AI Agent",
    chineseName: "智能体",
    category: "agent",
    oneLine: "能围绕目标规划、调用工具并迭代执行的 AI 系统。",
    explanation: "Agent 通常包含目标、上下文、工具、记忆、反馈和执行循环。",
    whyImportant: "它是理解自动化任务执行和 AI 工程产品的核心概念。",
    relatedTerms: ["ReAct", "Tool Calling", "Memory"],
    commonMistakes: ["把单次聊天回答也称为 Agent，而忽略状态和行动能力。"],
    examples: ["读取 issue、修改代码、运行测试、提交补丁。"],
    sourceRefs: [{ title: "ReAct", url: "https://arxiv.org/abs/2210.03629" }],
    difficulty: "beginner",
  },
  {
    slug: "tool-calling",
    fullName: "Tool Calling",
    chineseName: "工具调用",
    category: "agent",
    oneLine: "模型以结构化方式请求外部工具执行动作。",
    explanation: "Tool Calling 让模型从纯文本回答扩展到检索、计算、数据库查询和业务操作。",
    whyImportant: "它是构建可靠 Agent 和工作流自动化的基础能力。",
    relatedTerms: ["Agent", "Function Calling", "MCP"],
    commonMistakes: ["把工具调用结果当成模型推理本身；两者要分开记录。"],
    examples: ["模型输出调用 search(query) 的结构化参数。"],
    sourceRefs: [{ title: "OpenAI Function Calling", url: "https://platform.openai.com/docs/guides/function-calling" }],
    difficulty: "beginner",
  },
  {
    slug: "mcp",
    abbreviation: "MCP",
    fullName: "Model Context Protocol",
    chineseName: "模型上下文协议",
    category: "agent",
    oneLine: "连接模型应用和外部上下文/工具的开放协议。",
    explanation: "MCP 把工具、资源和提示以标准协议暴露给模型客户端，降低集成复杂度。",
    whyImportant: "它是理解现代 AI IDE 和工具生态的重要协议。",
    relatedTerms: ["Tool Calling", "Agent", "Context"],
    commonMistakes: ["把 MCP 当作某个模型专属功能；它是协议层。"],
    examples: ["通过 MCP 连接文件系统、数据库或设计工具。"],
    sourceRefs: [{ title: "Model Context Protocol", url: "https://modelcontextprotocol.io/" }],
    difficulty: "intermediate",
  },
  {
    slug: "embedding",
    fullName: "Embedding",
    chineseName: "向量表示",
    category: "retrieval",
    oneLine: "把文本、图像等对象映射到向量空间的表示。",
    explanation: "Embedding 让相似对象在向量空间中距离更近，是语义检索和推荐的基础。",
    whyImportant: "它连接自然语言和可计算的相似度搜索。",
    relatedTerms: ["Vector Database", "RAG", "Cosine Similarity"],
    commonMistakes: ["认为 embedding 相似就一定事实相关；它主要表达语义近似。"],
    examples: ["把问题和文档段落编码成向量后做相似度搜索。"],
    sourceRefs: [{ title: "Sentence-BERT", url: "https://arxiv.org/abs/1908.10084" }],
    difficulty: "beginner",
  },
  {
    slug: "vector-database",
    fullName: "Vector Database",
    chineseName: "向量数据库",
    category: "retrieval",
    oneLine: "面向向量相似度检索优化的数据存储系统。",
    explanation: "向量数据库支持近似最近邻搜索、元数据过滤和向量索引，常用于 RAG。",
    whyImportant: "它影响检索速度、召回率和生产系统稳定性。",
    relatedTerms: ["Embedding", "ANN", "RAG"],
    commonMistakes: ["只关注数据库品牌，不评估切分、索引和召回质量。"],
    examples: ["根据 query embedding 找到最相似的文档块。"],
    sourceRefs: [{ title: "FAISS", url: "https://faiss.ai/" }],
    difficulty: "beginner",
  },
  {
    slug: "reranker",
    fullName: "Reranker",
    chineseName: "重排序器",
    category: "retrieval",
    oneLine: "对初步检索结果再次排序，提高最终上下文质量。",
    explanation: "Reranker 通常用更昂贵但更精确的模型评估 query 和候选文档的相关性。",
    whyImportant: "它能明显改善 RAG 的引用命中率和回答质量。",
    relatedTerms: ["RAG", "BM25", "Embedding"],
    commonMistakes: ["认为 top-k 检索后直接塞给模型就足够。"],
    examples: ["先召回 50 段，再重排选 top 5。"],
    sourceRefs: [{ title: "Learning to Rank", url: "https://en.wikipedia.org/wiki/Learning_to_rank" }],
    difficulty: "intermediate",
  },
  {
    slug: "bm25",
    abbreviation: "BM25",
    fullName: "Best Matching 25",
    chineseName: "BM25 排名函数",
    category: "retrieval",
    oneLine: "基于词频和文档长度归一化的经典文本检索排序方法。",
    explanation: "BM25 是关键词检索中的强基线，常与 embedding 检索互补。",
    whyImportant: "它提醒我们语义检索不总是替代关键词检索。",
    relatedTerms: ["RAG", "Hybrid Search", "Reranker"],
    commonMistakes: ["在专业名词、代码和缩写检索中完全丢掉关键词方法。"],
    examples: ["用户搜 exact API 名称时，BM25 往往很强。"],
    sourceRefs: [{ title: "Okapi BM25", url: "https://en.wikipedia.org/wiki/Okapi_BM25" }],
    difficulty: "beginner",
  },
];
