import type { KnowledgeEntitySeed } from "@/server/knowledge/base";

export const DEFAULT_KNOWLEDGE_ENTITIES: KnowledgeEntitySeed[] = [
  {
    type: "person",
    name: "Shunyu Yao",
    slug: "shunyu-yao",
    aliases: ["姚顺雨"],
    oneLine: "ReAct、Reflexion 等 Agent 研究方向的重要作者之一。",
    whyImportant: "他的工作帮助把大模型推理、工具调用和自我反思连接成可执行 Agent 流程。",
    representativeWorks: ["ReAct", "Reflexion", "Tree of Thoughts"],
    relatedTerms: ["ReAct", "Reflexion", "Agent"],
    timeline: [
      { year: "2022", event: "发表 ReAct 工作" },
      { year: "2023", event: "参与 Reflexion / ToT 相关研究" },
    ],
    sourceRefs: [{ title: "Shunyu Yao homepage", url: "https://ysymyth.github.io/" }],
    lastVerifiedAt: "2026-05-24T00:00:00.000Z",
    confidence: "medium",
    selfCheckQuestion: "ReAct 和 Reflexion 分别解决 Agent 的哪类问题？",
  },
  {
    type: "company",
    name: "OpenAI",
    slug: "openai",
    aliases: ["OpenAI LP"],
    oneLine: "推动 GPT 系列、ChatGPT 和开发者 API 的 AI 公司。",
    whyImportant: "OpenAI 的模型和产品定义了很多现代 AI 应用、评测和开发接口的事实标准。",
    representativeWorks: ["GPT-4", "ChatGPT", "OpenAI API"],
    relatedTerms: ["RLHF", "Tool Calling", "Structured Outputs"],
    timeline: [
      { year: "2022", event: "发布 ChatGPT" },
      { year: "2023", event: "GPT-4 推动多模态与强推理应用" },
    ],
    sourceRefs: [{ title: "OpenAI", url: "https://openai.com/" }],
    lastVerifiedAt: "2026-05-24T00:00:00.000Z",
    confidence: "medium",
    selfCheckQuestion: "OpenAI 的 API 能力和 ChatGPT 产品能力有什么区别？",
  },
  {
    type: "company",
    name: "Anthropic",
    slug: "anthropic",
    aliases: ["Claude"],
    oneLine: "以 Claude 模型和 Constitutional AI 闻名的 AI 公司。",
    whyImportant: "Anthropic 是理解大模型安全、长上下文和企业 AI 产品的重要参照。",
    representativeWorks: ["Claude", "Constitutional AI"],
    relatedTerms: ["Alignment", "RLHF", "Long Context"],
    timeline: [
      { year: "2021", event: "公司成立" },
      { year: "2023", event: "Claude 系列进入主流 AI 助手竞争" },
    ],
    sourceRefs: [{ title: "Anthropic", url: "https://www.anthropic.com/" }],
    lastVerifiedAt: "2026-05-24T00:00:00.000Z",
    confidence: "medium",
    selfCheckQuestion: "Claude 和 GPT 系列在产品定位上有什么相似和差异？",
  },
  {
    type: "lab",
    name: "Google DeepMind",
    slug: "google-deepmind",
    aliases: ["DeepMind"],
    oneLine: "Google 旗下 AI 研究实验室，覆盖强化学习、科学 AI 和 Gemini。",
    whyImportant: "DeepMind 的 AlphaGo、AlphaFold 和 Gemini 连接了基础研究与大规模产品化。",
    representativeWorks: ["AlphaGo", "AlphaFold", "Gemini"],
    relatedTerms: ["Reinforcement Learning", "Protein Folding", "Multimodal"],
    timeline: [
      { year: "2016", event: "AlphaGo 展示深度强化学习影响力" },
      { year: "2023", event: "Gemini 系列进入大模型竞争" },
    ],
    sourceRefs: [{ title: "Google DeepMind", url: "https://deepmind.google/" }],
    lastVerifiedAt: "2026-05-24T00:00:00.000Z",
    confidence: "medium",
    selfCheckQuestion: "DeepMind 的科学 AI 成果和通用大模型成果分别是什么？",
  },
  {
    type: "lab",
    name: "Meta AI",
    slug: "meta-ai",
    aliases: ["FAIR", "Meta GenAI"],
    oneLine: "Meta 的 AI 研究与产品组织，覆盖 Llama、PyTorch 生态和 Meta AI 助手。",
    whyImportant: "Meta AI 是理解开放权重模型、研究基础设施和消费级 AI 助手竞争的重要节点。",
    representativeWorks: ["Llama", "PyTorch", "Meta AI"],
    relatedTerms: ["Open Weights", "Model Hub", "Alignment"],
    timeline: [
      { year: "2013", event: "Facebook AI Research 成立" },
      { year: "2023", event: "Llama 系列推动开放权重大模型生态" },
    ],
    sourceRefs: [{ title: "Meta AI", url: "https://ai.meta.com/" }],
    lastVerifiedAt: "2026-06-09T00:00:00.000Z",
    confidence: "medium",
    selfCheckQuestion: "Meta AI 的开放权重策略和闭源助手产品分别解决什么问题？",
  },
  {
    type: "company",
    name: "Mistral",
    slug: "mistral",
    aliases: ["Mistral AI"],
    oneLine: "提供开源与商业大模型、企业 AI 平台和 Agent 能力的法国 AI 公司。",
    whyImportant: "Mistral 是观察欧洲大模型生态、开放模型和企业部署选择的重要参照。",
    representativeWorks: ["Mistral", "Mixtral", "Le Chat"],
    relatedTerms: ["Open Weights", "Agent", "Fine-Tuning"],
    timeline: [
      { year: "2023", event: "Mistral AI 成立并发布开放模型" },
      { year: "2024", event: "Mixtral 和商业 API 进入主流开发者视野" },
    ],
    sourceRefs: [{ title: "Mistral AI", url: "https://mistral.ai/" }],
    lastVerifiedAt: "2026-06-09T00:00:00.000Z",
    confidence: "medium",
    selfCheckQuestion: "Mistral 的开放模型和商业平台分别适合哪些学习场景？",
  },
  {
    type: "company",
    name: "DeepSeek",
    slug: "deepseek",
    aliases: ["DeepSeek AI"],
    oneLine: "以推理和代码模型、开放权重发布和高性价比 API 受到关注的 AI 公司。",
    whyImportant: "DeepSeek 是理解模型效率、开源竞争和推理模型产品化的重要节点。",
    representativeWorks: ["DeepSeek-V3", "DeepSeek-R1", "DeepSeek Coder"],
    relatedTerms: ["Reasoning", "Code Agent", "Open Weights"],
    timeline: [
      { year: "2023", event: "DeepSeek 进入大模型和代码模型竞争" },
      { year: "2025", event: "DeepSeek-R1 推动推理模型讨论升温" },
    ],
    sourceRefs: [{ title: "DeepSeek", url: "https://www.deepseek.com/" }],
    lastVerifiedAt: "2026-06-09T00:00:00.000Z",
    confidence: "medium",
    selfCheckQuestion: "DeepSeek 的推理模型为什么会影响开发者选型？",
  },
  {
    type: "paper",
    name: "Attention Is All You Need",
    slug: "attention-is-all-you-need",
    aliases: ["Transformer paper"],
    oneLine: "提出 Transformer 架构的经典论文。",
    whyImportant: "Transformer 成为现代 LLM、机器翻译和多模态模型的基础架构。",
    representativeWorks: ["Transformer", "Self-Attention", "Multi-Head Attention"],
    relatedTerms: ["Transformer", "Self-Attention", "Embedding"],
    timeline: [{ year: "2017", event: "论文发布" }],
    sourceRefs: [{ title: "Attention Is All You Need", url: "https://arxiv.org/abs/1706.03762" }],
    lastVerifiedAt: "2026-05-24T00:00:00.000Z",
    confidence: "high",
    selfCheckQuestion: "Transformer 为什么可以不依赖 RNN/CNN 处理序列？",
  },
  {
    type: "benchmark",
    name: "SWE-bench",
    slug: "swe-bench",
    aliases: ["SWE Bench"],
    oneLine: "评测模型修复真实 GitHub issue 的软件工程基准。",
    whyImportant: "它更接近真实代码库维护任务，是 Agent 编码能力的重要指标。",
    representativeWorks: ["SWE-bench", "SWE-bench Verified"],
    relatedTerms: ["Agent", "Code Repair", "Benchmark"],
    timeline: [{ year: "2023", event: "SWE-bench 发布" }],
    sourceRefs: [{ title: "SWE-bench", url: "https://www.swebench.com/" }],
    lastVerifiedAt: "2026-05-24T00:00:00.000Z",
    confidence: "high",
    selfCheckQuestion: "SWE-bench 相比 HumanEval 更接近真实工程的原因是什么？",
  },
  {
    type: "benchmark",
    name: "HumanEval",
    slug: "humaneval",
    aliases: ["Human Eval"],
    oneLine: "评测 Python 函数补全能力的代码生成基准。",
    whyImportant: "它是理解代码模型能力早期对比的基础指标，但不能代表完整软件工程能力。",
    representativeWorks: ["pass@k", "Python function generation"],
    relatedTerms: ["Code Generation", "Benchmark", "SWE-bench"],
    timeline: [{ year: "2021", event: "OpenAI Codex 论文中使用 HumanEval" }],
    sourceRefs: [{ title: "HumanEval paper", url: "https://arxiv.org/abs/2107.03374" }],
    lastVerifiedAt: "2026-05-24T00:00:00.000Z",
    confidence: "high",
    selfCheckQuestion: "HumanEval 高分为什么不等于能修复真实项目 issue？",
  },
  {
    type: "open_source_project",
    name: "SWE-agent",
    slug: "swe-agent",
    aliases: ["SWE Agent"],
    oneLine: "面向真实软件工程任务的开源编码 Agent 框架。",
    whyImportant: "SWE-agent 把 SWE-bench 这样的真实 issue 基准和可执行 Agent 工作流连接起来。",
    representativeWorks: ["SWE-agent", "Agent-Computer Interface", "SWE-bench"],
    relatedTerms: ["SWE-bench", "Agent", "Code Repair"],
    timeline: [{ year: "2024", event: "SWE-agent 开源并围绕 SWE-bench 展示编码 Agent 能力" }],
    sourceRefs: [{ title: "SWE-agent GitHub", url: "https://github.com/princeton-nlp/SWE-agent" }],
    lastVerifiedAt: "2026-06-09T00:00:00.000Z",
    confidence: "medium",
    selfCheckQuestion: "SWE-agent 和 SWE-bench 的关系是什么？",
  },
  {
    type: "benchmark",
    name: "tau-bench",
    slug: "tau-bench",
    aliases: ["τ-bench", "Tool-Agent-User Interaction Benchmark"],
    oneLine: "评测工具型 Agent 在多轮用户交互和业务规则中完成任务的基准。",
    whyImportant: "tau-bench 把 Agent 能力从静态题目推进到工具调用、用户协作和策略约束的动态场景。",
    representativeWorks: ["tau-bench", "Tool-Agent-User Interaction"],
    relatedTerms: ["Agent", "Tool Calling", "Benchmark"],
    timeline: [{ year: "2024", event: "tau-bench 论文与基准发布" }],
    sourceRefs: [{ title: "tau-bench", url: "https://taubench.com/" }],
    lastVerifiedAt: "2026-06-09T00:00:00.000Z",
    confidence: "medium",
    selfCheckQuestion: "tau-bench 为什么比单轮静态 Benchmark 更接近 Agent 产品问题？",
  },
  {
    type: "tool",
    name: "Cursor",
    slug: "cursor",
    aliases: ["Cursor IDE"],
    oneLine: "面向 AI 辅助编程的编辑器。",
    whyImportant: "Cursor 代表了 AI IDE 形态：代码库上下文、编辑建议、聊天和 Agent 工作流结合。",
    representativeWorks: ["AI code editor", "Composer"],
    relatedTerms: ["AI IDE", "Code Agent", "Tool Calling"],
    timeline: [{ year: "2023", event: "AI IDE 产品形态快速增长" }],
    sourceRefs: [{ title: "Cursor", url: "https://cursor.com/" }],
    lastVerifiedAt: "2026-05-24T00:00:00.000Z",
    confidence: "medium",
    selfCheckQuestion: "AI IDE 相比普通聊天机器人多了哪些代码库上下文能力？",
  },
  {
    type: "tool",
    name: "Hugging Face",
    slug: "hugging-face",
    aliases: ["HF"],
    oneLine: "模型、数据集和开源机器学习生态平台。",
    whyImportant: "它是查找模型、数据集、demo 和开源推理工具的常用入口。",
    representativeWorks: ["Transformers", "Datasets", "Spaces"],
    relatedTerms: ["Open Source", "Model Hub", "Transformer"],
    timeline: [{ year: "2016", event: "公司成立" }],
    sourceRefs: [{ title: "Hugging Face", url: "https://huggingface.co/" }],
    lastVerifiedAt: "2026-05-24T00:00:00.000Z",
    confidence: "medium",
    selfCheckQuestion: "Hugging Face 的 Model Hub 和 Transformers 库分别解决什么问题？",
  },
  {
    type: "open_source_project",
    name: "LangChain",
    slug: "langchain",
    aliases: ["LangChain"],
    oneLine: "构建 LLM 应用和 Agent 工作流的开源框架。",
    whyImportant: "它把模型、检索、工具、链路和 Agent 抽象成可组合模块，是早期 LLM 应用生态代表。",
    representativeWorks: ["Chains", "Agents", "LangGraph"],
    relatedTerms: ["RAG", "Agent", "Tool Calling"],
    timeline: [{ year: "2022", event: "LangChain 开始流行" }],
    sourceRefs: [{ title: "LangChain", url: "https://www.langchain.com/" }],
    lastVerifiedAt: "2026-05-24T00:00:00.000Z",
    confidence: "medium",
    selfCheckQuestion: "LangChain 和直接调用模型 API 的区别是什么？",
  },
  {
    type: "concept",
    name: "Multi-Head Attention",
    slug: "multi-head-attention",
    aliases: ["MHA"],
    oneLine: "让多个 attention head 在不同表示子空间并行关注信息。",
    whyImportant: "它是 Transformer 能同时捕捉多种关系模式的核心机制。",
    representativeWorks: ["Transformer", "Attention Is All You Need"],
    relatedTerms: ["Self-Attention", "Q/K/V", "Transformer"],
    timeline: [{ year: "2017", event: "Transformer 论文推广该机制" }],
    sourceRefs: [{ title: "Attention Is All You Need", url: "https://arxiv.org/abs/1706.03762" }],
    lastVerifiedAt: "2026-05-24T00:00:00.000Z",
    confidence: "high",
    selfCheckQuestion: "多个 head 为什么比一个 head 更能表达不同关系？",
  },
];
